# Prefácio {.unnumbered}

Esse é um material construído para auxiliar os discentes do curso de Ciências Econômicas da Universidade Regional do Cariri no decorrer da disciplina de *Introdução à programação e à ciência de dados,* ministrada no terceiro período do curso. O material possui os instrumentos básicos para o acompanhamento do curso, incluindo explicações, comandos e exercícios. O material está organizado na ordem cronológica dos conteúdos repassados na disciplina de tal modo que essa ordem tem o intúito de conduzir o discente no aprendizado da programação computacional aplicada à economia em um cronograma planejado de acordo com as boas práticas do aprendizado da programação, evitando que o discente comece os estudos por conteúdos inadequados para os iniciantes nessa área.

O foco do material é a linguagem R, a mesma utilizada como objeto central da disciplina. Contudo, os métodos de aprendizado também podem ser expandidos para outras linguagens, desde que as devidas adaptações de vocabulário sejam consideradas. O material também possui um foco na análise de dados, desviando-se da programação computacional *"bruta"* devido a necessidade do curso e dos economistas em dominar os fundamentos básicos da utilização de dados.
